### ISSUE TITLE
图片链接有问题

### ISSUE THREAD

**Issue by wzxyisme** [miku-o/img-api#1]
图片链接点进去就直接下载下来了，并没有打开

**Comment by miku2365** [comment]
图片是从OneManager调用的直接访问会下载，但引用还是没问题的
```
<img src="url">
```
<img src="https://img.tlapi.ml/api.php">

```
![title](url)
```
![1](https://img.tlapi.ml/api.php)

**Comment by 66ccff-ml** [comment]
<img src="https://api-img.zhangyijia.eu.org//api.php">
